name: GitHub Actions CI
on: [push]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest]
    steps:
    - uses: actions/checkout@master
    - name: Execute Setup Script
      run: ./setup.sh